trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

name: $(Date:yyyyMMdd)-$(Rev:r)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: |
    pip3 install .
  displayName: 'Install dependencies'
- script: |
    python3 -m data_mass.populate do uat test
  displayName: 'Run tests'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- task: Docker@2
  displayName: "Build and push master branch"
  inputs:
    containerRegistry: 'Azure-Container-Registry-NonPROD-b2bgbacrint'
    repository: 'b2b-data-mass-application'
    Dockerfile: Dockerfile
    buildContext: ./
    tags: |
      latest
      $(build.buildNumber)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: Docker@2
  displayName: "Build and push development branch"
  inputs:
    containerRegistry: 'Azure-Container-Registry-NonPROD-b2bgbacrint'
    repository: 'b2b-data-mass-application'
    Dockerfile: Dockerfile
    buildContext: ./
    tags: dev-$(build.buildNumber)
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))