trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

name: $(Date:yyyyMMdd)-$(Rev:r)

steps:
- task: Docker@2
  displayName: "Build and push docker image"
  inputs:
    containerRegistry: 'Azure-Container-Registry-NonPROD-b2bgbacrint'
    repository: 'b2b-data-mass-application'
    Dockerfile: Dockerfile
    buildContext: ./
    tags: '$(build.buildNumber)'
